--insert into Borrows (Verleiher, Ausleiher, Ausleihdatum, Verfügbarkeitsdatum, Item) values ('Paul', 'Robert', '2020-04-21', '2020-04-24', 5001)
--DBCC CHECKIDENT ('[Items]', RESEED, 0);
--delete from Items
--truncate table Borrows
--select * from Borrows